language: scala
scala:
  - 2.12.15
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
jdk:
  - openjdk8
notifications:
  email:
    - fedeoasi@gmail.com
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.cache/coursier/